# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DHCPlanner
                                 A QGIS plugin
 automatically creates DHCs within a selection
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-14
        copyright            : (C) 2024 by Felix Lewandowski, HAW-Hamburg
        email                : felix.lewandowski@haw-hamburg.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DHCPlanner class from file DHCPlanner.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .dhc_planner import DHCPlanner
    return DHCPlanner(iface)
