---
  selection-layer-name: "selection"
  roads-layer-name: "roads"
  buildings-layer-name: "buildings"
  heat-demands-layer-name: "heat_demands"
  # possible strategies:
    # street-following: pipes have to be installed under the streets.
    # greenfield: no rules for pipe installation.
  installation-strategy: "street-following"
  # possible methods:
    # one-step: method that aims to calculate detailed and accurate results.
    # multi-step: heuristic method that aims to reduce needed computation resources as much as possible.
  distance-measuring-method: "custom"
  # possible methods:
    # centroids:
    # nearest_point:
    # custom:
  method: "multi-step"
  log-level: "info"
  roads-file-name: "roads.shp"
  buildings-file-name: "buildings.shp"
  crs: "EPSG:4839"
  save-graph: "False"
  load-graph: "False"
  graph-file-name: "saved_graph.json"

  # available strategies: none and single
  pivot-strategy: "single"

  fixed-cost: 100000 # ToDo: Check that there's a value here! It has to be above 0!!

  heat-capacity: 250 # 250 kW für Analyse!
  # in kW.

  insulation-factor: 0
  # insulation decreases heating demand by the specified percentage!

  minimum-heat-capacity-exhaustion: 40 # Analyse: kleinste mögliche Wärmequelle
  # in percent.

  trench-cost-per-cubic-m: 130.0

  excluded-road-fclasses:

  load-profile-factors:
    shopping-mall: 0.36
    residential: 0.4
    office: 0.47
    hospital: 0.5
    multi-family-residential-buildings: 0.51
    stand-alone-retail: 0.29
    secondary-school: 0.49
    full-service-restaurant: 0.39
    quick-service-restaurant: 0.45
    large-hotel: 0.6
    small-hotel: 0.53
    non-refrigerated-warehouse: 0.13
    supermarket: 0.24
    excluded: -1

  building-type-conversion:
    NULL_replacement: "residential"
    apartments: "multi-family-residential-buildings"
    house: "residential"
    detached: "residential"
    semidetached_house: "residential"
    allotment_house: "excluded"
    garage: "excluded"
    garages: "excluded"
    terrace: "multi-family-residential-buildings"
    residential: "residential"
    hut: "excluded"
    industrial: "non-refrigerated-warehouse"
    office: "office"
    shed: "non-refrigerated-warehouse"
    retail: "stand-alone-retail"
    school: "secondary-school"
    roof: "excluded"
    commercial: "stand-alone-retail"
    service: "stand-alone-retail"
    storage-tank: "excluded"
    greenhouse: "excluded"
    carport: "excluded"
    bungalow: "residential"
    warehouse: "non-refrigerated-warehouse"
    cabin: "excluded"
    kindergarten: "secondary-school"
    farm-auxiliary: "non-refrigerated-warehouse"
    hotel: "hotel"
    hospital: "hospital"
    church: "secondary-school"
    civic: "secondary-school"
    construction: "excluded"
    parking: "excluded"
    dormitory: "multi-family-residential-buildings"
    sports-centre: "stand-alone-retail"
    university: "secondary-school"
    farm: "excluded"
    bridge: "excluded"
    fire_station: "office"
    bunker: "excluded"
    static_caravan: "residential"
    public: "secondary-school"
    government: "office"
    train_station: "excluded"
    container: "excluded"
    sports_hall: "stand-alone-retail"
    supermarket: "supermarket"
    transportation: "excluded"
    houseboat: "residential"
    chapel: "secondary-school"
    conservatory: "secondary-school"
    toilets: "residential"
    guardhouse: "residential"
    silo: "excluded"
    stable: "excluded"
    college: "secondary-school"
    religious: "residential"
    kiosk: "stand-alone-retail"
    barn: "excluded"
    ruins: "excluded"
    ship: "excluded"
    hangar: "non-refrigerated-warehouse"
    grandstand: "excluded"
    mosque: "secondary-school"
    gatehouse: "residential"
    gym: "secondary-school"
    digester: "non-refrigerated-warehouse"
    boathouse: "non-refrigerated-warehouse"
    semi_detached: "residential"
    no: "excluded"
    electricity: "excluded"
    manufacture: "office"
    corridor: "excluded"
    dock: "non-refrigerated-warehouse"
    parish_hall: "secondary-school"
    barracks: "multi-family-residential-buildings"
    kingdom_hall: "secondary-school"
    presbytery: "residential"
    club_home: "residential"
    outbuilding: "non-refrigerated-warehouse"
    stadium: "excluded"
    museum: "secondary-school"
    tent: "excluded"
    greenhouse_horticult: "excluded"
    elevator: "excluded"
    tower: "excluded"
    proposed: "excluded"
    pavilion: "excluded"
    rectory: "residential"
    demolished: "excluded"
    hall: "secondary-school"
    community_center: "secondary-school"
    bakehouse: "office"
    parking_entrance: "excluded"
    water_tower: "excluded"
    fuel_station: "excluded"
    station: "excluded"
    riding_hall: "excluded"
    synagogue: "secondary-school"
    villa: "residential"
    transformer_tower: "excluded"
    semidetached_houseMM: "residential"
    shelter: "excluded"
    Waschkueche: "residential"
    restaurant: "full-service-restaurant"
    public_transport: "excluded"
    marquee: "excluded"
    carports: "excluded"
    workshop: "excluded"
    garageq: "excluded"
    disused: "excluded"
    residential;shop: "stand-alone-retail"
    police: "office"
    swimming_pool: "excluded"
    library: "secondary-school"
    almshouse: "residential"
    church_hall: "secondary-school"
    pool: "excluded"
    prefabricated: "residential"
    music_venue: "secondary-school"
    nightclub: "stand-alone-retail"
    data_center: "non-refrigerated-warehouse"
    clubhouse: "residential"
    bell_tower: "excluded"
    Supermarket/Mall: "shopping-mall"
    slurry_tank: "excluded"
    glasshouse: "excluded"
    Company: "office"
    aviary: "non-refrigerated-warehouse"
    gymnasium: "stand-alone-retail"
    residential;house: "residential"
    cathedral: "secondary-school"
    shrine: "excluded"
    kiosk_minigolf: "stand-alone-retail"
    property_management: "residential"
    part: "excluded"
    scaffold: "excluded"
    water: "excluded"
    tunnel: "excluded"
    demolished:garage: "excluded"
    club: "stand-alone-retail"
    garden_house: "excluded"
    shipping_container: "excluded"
    cowshed: "excluded"
    conta: "excluded"

  street-type-multipliers:
      bridleway: 1.0
      cycleway: 1.0
      footway: 1.0
      living_street: 1.0
      motorway: 1.0
      motorway_link: 1.0
      path: 1.0
      pedestrian: 1.0
      primary: 1.0
      primary_link: 1.0
      residential: 1.0
      secondary: 1.0
      secondary_link: 1.0
      service: 1.0
      steps: 1.0
      tertiary: 1.0
      tertiary_link: 1.0
      track: 1.0
      track_grade1: 1.0
      track_grade2: 1.0
      track_grade3: 1.0
      track_grade4: 1.0
      track_grade5: 1.0
      trunk: 1.0
      trunk_link: 1.0
      unclassified: 1.0
      unknown: 1.0